-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.automatizacion_ejecuciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  automatizacion_id uuid,
  prospecto_id uuid,
  estado text DEFAULT 'pendiente'::text CHECK (estado = ANY (ARRAY['pendiente'::text, 'ejecutando'::text, 'completado'::text, 'fallido'::text, 'cancelado'::text])),
  trigger_data jsonb DEFAULT '{}'::jsonb,
  resultado jsonb DEFAULT '{}'::jsonb,
  error_message text,
  iniciado_at timestamp with time zone,
  completado_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT automatizacion_ejecuciones_pkey PRIMARY KEY (id),
  CONSTRAINT automatizacion_ejecuciones_prospecto_id_fkey FOREIGN KEY (prospecto_id) REFERENCES public.prospectos(id),
  CONSTRAINT automatizacion_ejecuciones_automatizacion_id_fkey FOREIGN KEY (automatizacion_id) REFERENCES public.automatizaciones(id)
);
CREATE TABLE public.automatizaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  nombre text NOT NULL,
  descripcion text,
  activa boolean DEFAULT true,
  trigger_config jsonb NOT NULL,
  actions_config jsonb NOT NULL,
  condiciones jsonb DEFAULT '{}'::jsonb,
  total_ejecutado integer DEFAULT 0,
  total_exitoso integer DEFAULT 0,
  total_fallido integer DEFAULT 0,
  schedule_config jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  CONSTRAINT automatizaciones_pkey PRIMARY KEY (id),
  CONSTRAINT automatizaciones_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.ejecutivos(id)
);
CREATE TABLE public.conversaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  external_id text UNIQUE,
  phone_number text NOT NULL,
  contact_name text,
  prospecto_id uuid,
  assigned_to uuid,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'closed'::text, 'archived'::text])),
  last_message_at timestamp with time zone DEFAULT now(),
  message_count integer DEFAULT 0,
  unread_count integer DEFAULT 0,
  contact_info jsonb DEFAULT '{}'::jsonb,
  tags ARRAY DEFAULT '{}'::text[],
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  notas text,
  CONSTRAINT conversaciones_pkey PRIMARY KEY (id),
  CONSTRAINT conversaciones_prospecto_id_fkey FOREIGN KEY (prospecto_id) REFERENCES public.prospectos(id),
  CONSTRAINT conversaciones_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.ejecutivos(id)
);
CREATE TABLE public.ejecutivos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  nombre text NOT NULL,
  email text NOT NULL UNIQUE CHECK (email ~ '^[^@]+@[^@]+\.[^@]+$'::text),
  telefono text,
  avatar_url text,
  carreras_especializacion ARRAY DEFAULT '{}'::text[],
  regiones_cobertura ARRAY DEFAULT '{}'::text[],
  max_prospectos_simultaneos integer DEFAULT 50 CHECK (max_prospectos_simultaneos > 0),
  prospectos_activos integer DEFAULT 0,
  tasa_conversion numeric DEFAULT 0.00,
  total_conversiones integer DEFAULT 0,
  horario_inicio time without time zone DEFAULT '09:00:00'::time without time zone,
  horario_fin time without time zone DEFAULT '18:00:00'::time without time zone,
  timezone text DEFAULT 'America/Santiago'::text,
  dias_trabajo ARRAY DEFAULT '{1,2,3,4,5}'::integer[],
  activo boolean DEFAULT true,
  disponible boolean DEFAULT true,
  ultimo_login timestamp with time zone,
  configuracion jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT ejecutivos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fuentes_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  nombre text NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['formulario_web'::text, 'landing_page'::text, 'facebook_ads'::text, 'google_ads'::text, 'whatsapp_bot'::text, 'referido'::text])),
  url text,
  activa boolean DEFAULT true,
  configuracion jsonb DEFAULT '{}'::jsonb,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  campos_requeridos ARRAY DEFAULT '{}'::text[],
  campos_opcionales ARRAY DEFAULT '{}'::text[],
  mensaje_gracias text,
  redirect_url text,
  total_leads integer DEFAULT 0,
  leads_hoy integer DEFAULT 0,
  tasa_conversion numeric DEFAULT 0.00,
  costo_por_lead numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT fuentes_leads_pkey PRIMARY KEY (id)
);
CREATE TABLE public.leads_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  prospecto_id uuid,
  fuente_id uuid,
  session_id text,
  ip_address inet,
  user_agent text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  pais text,
  ciudad text,
  region text,
  formulario_id text,
  landing_page_id text,
  campana_id text,
  primera_visita timestamp with time zone,
  conversion timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT leads_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT leads_tracking_fuente_id_fkey FOREIGN KEY (fuente_id) REFERENCES public.fuentes_leads(id),
  CONSTRAINT leads_tracking_prospecto_id_fkey FOREIGN KEY (prospecto_id) REFERENCES public.prospectos(id)
);
CREATE TABLE public.mensajes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  conversacion_id uuid,
  external_id text,
  content text NOT NULL,
  message_type text DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'image'::text, 'document'::text, 'audio'::text, 'video'::text, 'location'::text, 'contact'::text])),
  type text NOT NULL CHECK (type = ANY (ARRAY['user'::text, 'bot'::text, 'agent'::text])),
  sender_id text,
  sender_name text,
  is_read boolean DEFAULT false,
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT mensajes_pkey PRIMARY KEY (id),
  CONSTRAINT mensajes_conversacion_id_fkey FOREIGN KEY (conversacion_id) REFERENCES public.conversaciones(id)
);
CREATE TABLE public.prospectos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  nombre text NOT NULL,
  email text CHECK (email ~ '^[^@]+@[^@]+\.[^@]+$'::text OR email IS NULL),
  telefono text,
  whatsapp text NOT NULL CHECK (whatsapp ~ '^\\+?[0-9\\s\\-\\(\\)]{8,20}$'::text),
  edad integer,
  ocupacion text,
  carrera_interes text,
  nivel_educacion text,
  experiencia_previa text,
  region text,
  ciudad text,
  pais text DEFAULT 'Chile'::text,
  estado text DEFAULT 'nuevo'::text CHECK (estado = ANY (ARRAY['nuevo'::text, 'contactado'::text, 'interesado'::text, 'matriculado'::text, 'descartado'::text])),
  nivel_interes text DEFAULT 'medio'::text CHECK (nivel_interes = ANY (ARRAY['bajo'::text, 'medio'::text, 'alto'::text, 'muy_alto'::text])),
  assigned_to uuid,
  ejecutivo_asignado_at timestamp with time zone,
  fuente text DEFAULT 'whatsapp_bot'::text CHECK (fuente = ANY (ARRAY['whatsapp_bot'::text, 'web_form'::text, 'facebook_ads'::text, 'google_ads'::text, 'referido'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  notas text,
  tags ARRAY,
  ultimo_contacto timestamp with time zone,
  proximo_seguimiento timestamp with time zone,
  CONSTRAINT prospectos_pkey PRIMARY KEY (id),
  CONSTRAINT prospectos_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.ejecutivos(id)
);